version: "0"
services:
  k6:
    image: grafana/k6:latest
    volumes:
      - ./tests:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    command: run /scripts/performance.js

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana:/etc/grafana/provisioning
    depends_on:
      - influxdb
